apiVersion: v1
kind: Service
metadata:
  name: event-db-external-service
spec:
  externalTrafficPolicy: Local
  ports:
    - name: client
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: event-db-svc
  type: NodePort